### ISSUE TITLE
Error: Invalid trytes length. Expected trytes of even length.. fetching data example 5-2 

### ISSUE THREAD

**Issue by yehia67** [iota-community/javascript-iota-workshop#15]
Hey I just run the program 5.1 to send data and it work correctly then 5.2 to fetch data. But it gave me this error
```
Error: Invalid trytes length. Expected trytes of even length.
    at Object.exports.trytesToAscii (/home/yehia/Documents/Projects/IOTA/javascript-iota-workshop/node_modules/@iota/converter/out/converter/src/ascii.js:76:15)
    at iota.findTransactionObjects.then.response (/home/yehia/Documents/Projects/IOTA/javascript-iota-workshop/code/5.2-fetch-data.js:27:28)
    at tryCatcher (/home/yehia/Documents/Projects/IOTA/javascript-iota-workshop/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/yehia/Documents/Projects/IOTA/javascript-iota-workshop/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/yehia/Documents/Projects/IOTA/javascript-iota-workshop/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/yehia/Documents/Projects/IOTA/javascript-iota-workshop/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/yehia/Documents/Projects/IOTA/javascript-iota-workshop/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/home/yehia/Documents/Projects/IOTA/javascript-iota-workshop/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/yehia/Documents/Projects/IOTA/javascript-iota-workshop/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/yehia/Documents/Projects/IOTA/javascript-iota-workshop/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/yehia/Documents/Projects/IOTA/javascript-iota-workshop/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by satishrao** [comment]
I too got the same error . Any help pls

**Comment by Thoralf-M** [comment]
This happens if there is an uneven length of txs at this address, because then the messages together will also have an uneven length, the same happens if the message is so short that there is only one transaction, in that case you could just remove one Tryte with msg.slice(0, -1) before you convert it
